EncapPackages: Run bcfg2-site install as part of all since it (should be) convergant; also start up ostiary service if it hasn't already been started.
git-svn-id: https://svn.mcs.anl.gov/repos/bcfg/trunk/bcfg2@2115 ce84e21b-d406-0410-9b95-82705330c041

diff --git a/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl b/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
--- a/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
+++ b/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
@@ -81,6 +81,17 @@ else
     touch ${BASEDIR}/sbin/.SENTINEL_SITE
 fi
 
+if [ ! -h /service/ostiary ]; then
+    if [ -d /usr/local/var/svc.d/ostiary ]; then
+        ln -s /usr/local/var/svc.d/ostiary /service/ostiary
+    else
+        printf "ERROR: /usr/local/var/svc.d/ostiary does not exist.\n"
+        exit 1
+    fi
+else
+    printf "INFO: /service/ostiary already exists, not replacing...\n"
+fi
+
 //if int(@BCFG2_CLIENT_RUN_INTERVAL_SECONDS) > 0
 if [ ! -h /service/bcfg2-client ]; then
     if [ -d /usr/local/var/svc.d/bcfg2-client ]; then
