EncapPackages: Add bcfg2-client "daemon" start to bcfg2-site
git-svn-id: https://svn.mcs.anl.gov/repos/bcfg/trunk/bcfg2@2108 ce84e21b-d406-0410-9b95-82705330c041

diff --git a/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl b/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
--- a/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
+++ b/encap/src/bcfg2-site/bcfg2-site-RENAME/postinstall.tmpl
@@ -1,3 +1,8 @@
+#include "site-settings.conf"
+#compiler-settings
+cheetahVarStartToken = @
+commentStartToken = //
+#end compiler-settings
 #!/bin/sh -e
 
 umask 002
@@ -75,6 +80,19 @@ else
     rmcp $PKGDIR/sbin/ost-bcfg2.sh ${BASEDIR}/sbin/
     touch ${BASEDIR}/sbin/.SENTINEL_SITE
 fi
+
+//if int(@BCFG2_CLIENT_RUN_INTERVAL_SECONDS) > 0
+if [ ! -h /service/bcfg2-client ]; then
+    if [ -d /usr/local/var/svc.d/bcfg2-client ]; then
+        ln -s /usr/local/var/svc.d/bcfg2-client /service/bcfg2-client
+    else
+        printf "ERROR: /usr/local/var/svc.d/bcfg2-client does not exist.\n"
+        exit 1
+    fi
+else
+    printf "INFO: /service/bcfg2-client already exists, not replacing...\n"
+fi
+//end if
 
 printf "Finished ${ENCAP_PKGNAME} postinstall script.\n"
 
